name: build_configuration_app

on: [push]
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
    - id: s01
      run: echo "github ${{github.ref_name}}"
    - run: echo "before" && ls -l
    - id: s02
      uses: actions/setup-node@v4
      with:
        node-version: "24"
    - id: s03
      uses: actions/checkout@v5
    - run: echo "after" && ls -l

    - id: s04
      run: npm i -g @angular/cli && npm cl && echo "installed"  
    - id: s05
      run: ng build

    - id: s06
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: './dist'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1


